### ISSUE TITLE
【依頼】フリマアプリ挙動確認	

### ISSUE THREAD

**Issue by tech-arichan** [tech-arichan/furima-29076#10]
#URL
https://furima-29076.herokuapp.com/

#Basic認証のIDとパスワード
ID:admin / password:2222

#出品者用のメールアドレスとパスワード　
mail : ari@ari  /  pass : aaaaaa1

#購入者用のメールアドレスとパスワード　
mail : aaa@aaa  /  pass : aaaaaa1

#購入用カードの番号・期限・セキュリティコード　
番号 : 4242424242424242   /   期限 : month 12. year 22   /   cvc : 123

**Comment by kana-create** [comment]
安永さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
